### ISSUE TITLE
Misalignment: general use cases

### ISSUE THREAD

**Issue by KrzysztofMadejski** [themoonsheep/moonsheep.org#2] opened 2018-02-19 13:21 UTC
It would be nice if the text and icons were aligned horizontally.

![misalign1](https://user-images.githubusercontent.com/849975/36379786-d02c16b2-1577-11e8-91a3-5f2970083ab6.png)

**Comment by simonfossom** [comment] 2018-02-19 14:26
Adjusted it in design!

**Comment by IronRunes** [comment] 2018-02-19 19:03
fixed in [https://github.com/themoonsheep/moonsheep.org/commit/ac836c94d0c6e2ce3015d91d9204dab04b697212](url)

**Comment by simonfossom** [comment] 2018-02-28 10:16
It's not by design. We talked that you'll put this in the html table... 
![image](https://user-images.githubusercontent.com/8134850/36782270-b6504684-1c78-11e8-8af7-98aa87eb8784.png)

**Comment by IronRunes** [comment] 2018-02-28 12:02
I thought we were putting the pros and cons in an html table (done that, btw). I aligned icons & related text horizontally, as per Krzystof's request.
No biggie though, can do

**Comment by KrzysztofMadejski** [comment] 2018-02-28 14:03
On my chrome (Version 64.0.3282.186, Ubuntu 17.04) the text is aligned, but icons still are not aligned horizontally (see below).

Let me know @IronRunes if I should test some css live.

![screenshot from 2018-02-28 09-01-45](https://user-images.githubusercontent.com/849975/36791532-22e50e78-1c66-11e8-9aae-944ab4c278ca.png)

**Comment by IronRunes** [comment] 2018-03-02 15:14
so you want everything aligned horizontally, and not reciprocally (i.e. icon aligned to text, as is now). 
ok, will do.

**Comment by IronRunes** [comment] 2018-03-02 15:26
Done

**Closed as completed** 2018-03-02 16:30 UTC
